name: Second Hello World
on:
  workload_dispatch

jobs:
  steps:
    first-step:
      runs-on: ubuntu:latest
      steps:
        - run: echo Hello World

    second-step-python:
      runs-on: ubuntu:latest
      steps:
        - run: print("Hello World")
          shell: python
    
    third-step-java:
      steps:
        - uses: actions/hello-world-javascript-action
          with:
            who-to-great: "World and Aleandro"
